name: asakusafw-publish

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      HADOOP_VERSION: 2.10.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache for Maven
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/asakusafw
          key: maven-publish-${{ hashFiles('pom.xml', '.mvn/wrapper/maven-wrapper.properties') }}
          restore-keys: |
            maven-publish-

      - name: Cache for Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-publish-${{ hashFiles('pom.xml', '.mvn/wrapper/maven-wrapper.properties', 'gradle/build.gradle', 'gradle/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-publish-

      - name: Cache hadoop
        uses: actions/cache@v2
        with:
          path: |
            /opt/hadoop-${{env.HADOOP_VERSION}}
          key: hadoop-${{env.HADOOP_VERSION}}
          restore-keys: |
            hadoop-${{env.HADOOP_VERSION}}

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          server-id: com.asakusafw.snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Setup Hadoop
        run: |
          if [ ! -e /opt/hadoop-${HADOOP_VERSION} ]; then
            curl -sL https://archive.apache.org/dist/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz | tar -xz -C /opt
          fi

      # - name: Publish Maven modules
      #   run: |
      #     ./mvnw -B clean deploy -DskipTests
      #   env:
      #     MAVEN_USERNAME: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     MAVEN_PASSWORD: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.count=3
      #     HADOOP_CMD: /opt/hadoop-${{env.HADOOP_VERSION}}/bin/hadoop

      - name: Test Gradle modules
        run: |
          cd gradle
          ./gradlew -i clean build install uploadArchives
          cd -
        env:
          MAVEN_USERNAME: ${{ secrets.AWS_ACCESS_KEY_ID }}
          MAVEN_PASSWORD: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: '**/TEST-*.xml'
          check_name: 'test_report'
          github_token: ${{ secrets.GITHUB_TOKEN }}

