name: asakusafw-test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      HADOOP_VERSION: 2.10.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache for Maven
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/asakusafw
          key: maven-test-${{ hashFiles('pom.xml', '.mvn/wrapper/maven-wrapper.properties') }}
          restore-keys: |
            maven-test-

      - name: Cache for Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-test-${{ hashFiles('pom.xml', '.mvn/wrapper/maven-wrapper.properties', 'gradle/build.gradle', 'gradle/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-test-

      - name: Cache hadoop
        uses: actions/cache@v2
        with:
          path: |
            /opt/hadoop-${{env.HADOOP_VERSION}}
          key: hadoop-${{env.HADOOP_VERSION}}
          restore-keys: |
            hadoop-${{env.HADOOP_VERSION}}

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Setup Hadoop
        run: |
          if [ ! -e /opt/hadoop-${HADOOP_VERSION} ]; then
            curl -sL https://archive.apache.org/dist/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz | tar -xz -C /opt
          fi

      - name: Test Maven modules
        run: |
          ./mvnw -B clean test
        env:
          MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.count=3
          HADOOP_CMD: /opt/hadoop-${{env.HADOOP_VERSION}}/bin/hadoop

      - name: Test Gradle modules
        run: |
          cd gradle
          ./gradlew -i clean check
          cd -

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: '**/TEST-*.xml'
          check_name: 'test_report'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  static_analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache for Maven
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/asakusafw
          key: maven-static-analysis-${{ hashFiles('pom.xml', '.mvn/wrapper/maven-wrapper.properties') }}
          restore-keys: |
            maven-static-analysis-

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Static analysys Maven modules
        run: |
          ./mvnw -B clean compile test-compile com.github.spotbugs:spotbugs-maven-plugin:spotbugs checkstyle:checkstyle
        env:
          MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.count=3

      - name: Publish SpotBugs Report
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugsXml.xml'
          name: 'spotbugs_report'

      - name: Publish Checkstyle Report
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/checkstyle-result.xml'
          name: 'checkstyle_report'
